### ISSUE TITLE
Placeholders returning "<invalid_argument>"

### ISSUE THREAD

**Issue by Cosmiiko** [megamichiel/AnimatedMenu#14]
My placeholders (actually the %player_name% from the example menus) are returning "<invalid_argument>" and I have no idea why nor if it's on this plugin's side or on the PlaceholderAPI plugin side.

![image](https://user-images.githubusercontent.com/29412451/42158413-a3a8dc10-7df0-11e8-8512-0243ed65a569.png)
![image](https://user-images.githubusercontent.com/29412451/42158423-aa784b84-7df0-11e8-9145-56dc40ac74a7.png)

**Comment by Matthysse** [comment]
Me too, there is a real problem with PlaceHolders API in this plugin, no color for LuckPerms placeholders (there is color is the scoreboard) And there is invalid_argument with %player_name% but in the score board it work and say my name.

**Comment by Cosmiko5700** [comment]
@Matthysse Your scoreboard probably use %player%, which works.
By the way as the problem is from the placeholder plugin, this can be closed.

**Comment by Matthysse** [comment]
No, it's really the plugin! I used temporaly %player_name% in the scoreboard, there isn't my name is the scoreboard normally. And i use %player% for the head in the statistics menu, and it show a steve head. It worked 2 days ago, and know no anymore. I don't understand.
![2018-07-05_16 22 20](https://user-images.githubusercontent.com/32510957/42331270-4a731fb6-8075-11e8-91ab-800cd9867571.png)

**Comment by Matthysse** [comment]
Don't say that it can be closed when you don't know what you are talking about...

**Comment by Matthysse** [comment]
Ok! I found the fix! AnimatedMenu isn't compatible with the latest version of the Player expansion! I downloaded the 1.5.0 (not the 1.5.1) version and renamed it in "Expansion-Player.jar" instead of "PAPI-Expansion-Player" when you download it!
