### ISSUE TITLE
Admin mode partially crashes plugin.

### ISSUE THREAD

**Issue by Zendrex** [megamichiel/AnimatedMenu#3]
Seems that adding `Admin: true` causes the menu's to partially crash.

There is no error, however all animation freezes, regardless of removing the option, or reload. A forced server restart is needed in order for it to fix.

Also, there is no documentation on it. I know this was based of my feature request, however even a slight example of how to configure this would be greatly appreciated.

-Zendrex

**Comment by megamichiel** [comment]
In recent updates I've been saying that I temporarily halted updating the configuration tutorials because I am working on updates for it.
I cannot recreate this problem myself. Could you perhaps send me your menu's configuration?

**Comment by Zendrex** [comment]
@megamichiel Simply added `Admin: true` to the menu, reloaded/restarted and it froze the menu's. Anything else I should be doing before hand?
